# **NumPy Basics**


## **Creating a Basic Array**


In [1]:
   import numpy as np
   arr1=np.array([1,2,3])
   arr2=np.array(['a','b','c','d','e'])
   arr3= np.array((1, 2, 3, 4, 5)) # You can also pass a tuple to creat an Array
   print(arr1)
   print(arr2)
   print(arr3)
   print(type(arr1))

[1 2 3]
['a' 'b' 'c' 'd' 'e']
[1 2 3 4 5]
<class 'numpy.ndarray'>


Arrays using ***np.zeros(), np.ones(), np.arange()***

In [2]:
   import numpy as np
   a=np.zeros(3)
   b=np.ones(5)
   c=np.arange(10)
   d=np.arange(2,9)   # To specify start and stop
   e=np.arange(1,10,2) # To specify start and stop with step size
   print(a)
   print(b)
   print(c)
   print(d)
   print(e)

[0. 0. 0.]
[1. 1. 1. 1. 1.]
[0 1 2 3 4 5 6 7 8 9]
[2 3 4 5 6 7 8]
[1 3 5 7 9]


## **NdArray (N-Dimensional Array)**

 **A 2-Dimensional Array**

In [5]:
   import numpy as np
   arr1=np.array([[1,2,3],[4,5,6]])
   arr2=np.array([[1,2,3],[4,5,6],[7,8,9]])
   arr3=np.array([['a','b','c'],['d','e','f']])
   
   #creates a 3X3 array with all zeros
   zeros=np.zeros((3,3))
   
   #creates a 2X2 array with all ones
   ones=np.ones((2,2),dtype='int64')  #specify the type with (dtype) parameter 
   
   print(arr1)
   print(arr2)
   print(arr3)
   print(zeros)
   print(ones)

[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[['a' 'b' 'c']
 ['d' 'e' 'f']]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1 1]
 [1 1]]


NumPy provides some cool methods you can check the number of dimensions using ***ndim***

In [6]:
   import numpy as np

   a = np.array(42)
   b = np.array([1, 2, 3, 4, 5])
   c = np.array([[1, 2, 3], [4, 5, 6]])
   d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

   print(a.ndim)
   print(b.ndim)
   print(c.ndim)
   print(d.ndim)

0
1
2
3


**Basic Operations with Arrays**

In [7]:
   import numpy as np
   arr1=np.array([5,5,5,5])
   arr2=np.array([3,3,3,3])
   c=arr1+arr2
   d=arr1-arr2
   e=arr1/arr2
   print(arr1)
   print(arr2)
   print(c) # addition
   print(d) # subtraction
   print(e) # division
   print("Adding one to all elements:",c+1)
   print("Subtracting one from all elements:",d-1)

[5 5 5 5]
[3 3 3 3]
[8 8 8 8]
[2 2 2 2]
[1.66666667 1.66666667 1.66666667 1.66666667]
Adding one to all elements: [9 9 9 9]
Subtracting one from all elements: [1 1 1 1]


## **Array Indexing and Slicing**

### **Array Indexing**

In [9]:
   import numpy as np
   arr1= np.array([3,2,3,4])
   arr2= np.array([2,1,1,3])
   arr3= np.array(['D','e','V','I','n','c','e','p','t'])
   arr4= np.array([[1,2,3,4,5], [6,7,8,9,10]])
   print(arr1[0]) # prints first element
   print(arr1[-1]) # prints last element
   print(arr2[2]) # prints third element
   print(arr3[0]) # prints first element
   print(arr4[1][3]) #prints 9
   print(arr4[1,3]) # Or you can use this type 

3
4
1
D
9
9


### **Array Slicing**

In [10]:
   import numpy as np
   arr1=np.array(['D','e','V','I','n','c','e','p','t'])
   arr2=np.array([1,2,3,4,5,6,7,8,9])
   
   #2-D Slicing
   arr3=np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
   
   print(arr1[:3]) # default is taken as 0
   print(arr1[0:3])
   print(arr1[3:]) # taken till the end
   print(arr1[::2])
   
   print(arr2[-4:-1])
   print(arr2[::2]) # step size as 2
   
   # 2-D Slicing
   print(arr3[1,1:4])
   print(arr3[0:2, 2])
   print(arr3[0:2, 1:4])

['D' 'e' 'V']
['D' 'e' 'V']
['I' 'n' 'c' 'e' 'p' 't']
['D' 'V' 'n' 'e' 't']
[6 7 8]
[1 3 5 7 9]
[7 8 9]
[3 8]
[[2 3 4]
 [7 8 9]]


**All in One Example**

In [11]:
   import numpy as np
   data = np.array([1, 2, 3])
   print(data[1])
   print(data[0:2])
   print(data[1:])
   print(data[-2:])

2
[1 2]
[2 3]
[2 3]


# **Numpy Functions**

## **NumPy Array Shape**

In [12]:
   import numpy as np
   arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
   arr1= np.array([1,2,3,4])

   print(arr.shape)
   print(arr1.shape)

(2, 4)
(4,)


**All in One Example**

In [16]:
   array_example = np.array([[[0, 1, 2, 3],
                            [4, 5, 6, 7]],

                           [[0, 1, 2, 3],
                            [4, 5, 6, 7]],

                           [[0 ,1 ,2, 3],
                            [4, 5, 6, 7]]])
 
   print('No of dimensions of the array:',array_example.ndim)     # .ndim for dimensions
   print('Total no of elements of the array:',array_example.size) # .size for size
   print('Shape of the array:',array_example.shape)                # .shape for shape

No of dimensions of the array: 3
Total no of elements of the array: 24
Shape of the array: (3, 2, 4)


## **NumPy Array Reshaping**

**Reshape from 1-Dimensional to 2-Dimensional**

In [17]:
   import numpy as np
   arr1 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
   newarr1 = arr1.reshape(4, 3)
   arr2 = np.array(['D','e','V','I','n','c','e','p','t'])
   newarr2 = arr2.reshape(3,3)
   print(newarr1)
   print(newarr2)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[['D' 'e' 'V']
 ['I' 'n' 'c']
 ['e' 'p' 't']]


**Reshape from 1-Dimensional to 3-Dimensional**

In [18]:
   import numpy as np
   arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
   newarr = arr.reshape(2, 3, 2)
   print(newarr)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


**Multi-Dimensional Array into 1-Dimensional Array**

In [19]:
   import numpy as np
   arr = np.array([[1, 2, 3], [4, 5, 6]])
   newarr = arr.reshape(-1)
   print(newarr)

[1 2 3 4 5 6]


## **NumPy Sorting and Searching**

### **NumPy Sorting**

In [20]:
   import numpy as np
   arr1 = np.array([3, 2, 0, 1])
   arr2 = np.array(['red','blue','green'])
   
   # 2-D array
   arr3 = np.array([[3, 2, 4], [5, 0, 1]])
   
   print(np.sort(arr1))
   print(np.sort(arr2))
   print(np.sort(arr3))

[0 1 2 3]
['blue' 'green' 'red']
[[2 3 4]
 [0 1 5]]


### **NumPy Searching**

**where() :**

In [21]:
   import numpy as np
   arr1 = np.array([1, 2, 3, 4, 5, 4, 4])
   x = np.where(arr1 == 4)
   y = np.where(arr1%2 == 0)
   z = np.where(arr1%2 == 1)
   print(x)
   print(y)
   print(z)

(array([3, 5, 6]),)
(array([1, 3, 5, 6]),)
(array([0, 2, 4]),)


**searchsorted() :**

In [22]:
   import numpy as np
   arr1 = np.array([6, 7, 8, 9])
   x = np.searchsorted(arr1, 7)
   print(x)
   
   # Multiple values
   arr2 = np.array([1, 3, 5, 7])
   y = np.searchsorted(arr2, [2, 4, 6])
   print(y)

1
[1 2 3]


## **Mean, Median, Mode**

### **Mean**

In [23]:
   import numpy as np
   arr=np.array([19,13,18,21,44,17,12,31,37,8,12,27])
   x=np.mean(arr)
   print(x)

21.583333333333332


### **Median**

In [24]:
   import numpy
   # For one value in the middle
   speed = [99,86,87,88,111,86,103,87,94,78,77,85,86]
   x = numpy.median(speed)
   print(x)
   
   # For two values in the middle
   speed1 = [99,86,87,88,86,103,87,94,78,77,85,86]
   y = numpy.median(speed1)
   print(y)

87.0
86.5


### **Mode**

In [25]:
   from scipy import stats
   speed = [99,86,87,88,111,86,103,87,94,78,77,85,86]
   x = stats.mode(speed)
   print(x)

ModeResult(mode=array([86]), count=array([3]))


## **Standard Deviation (σ)**

In [26]:
   import numpy
   speed = [86,87,88,86,87,85,86]
   x = numpy.std(speed)
   print(x)
   
   speed1 = [32,111,138,28,59,77,97]
   y = numpy.std(speed1)
   print(y)

0.9035079029052513
37.84501153334721


# **Practice all you want and play with the code as much as you want..**
